### PR TITLE
Provide a `list` command to list available visualisations

### PR DESCRIPTION
**Pull request by abailly-iohk**
Also provide a `run` command to, well, run the simulation and rename some types to use less abbreviations.

### CODE REVIEW

**Review by wenkokke — APPROVED** [review]
Looks good. Oddly, I already formatted the code with fourmolu in an earlier commit. I should investigate whether or not my formatter is picking up on the configuration.

**Comment by abailly-iohk** [comment]
I have been bitten in the past by different versions of fourmolu. I am not using nix so perhaps it's _my_ version that's misaligned with everyone else's?

**Comment by wenkokke** [comment]
> I have been bitten in the past by different versions of fourmolu. I am not using nix so perhaps it's _my_ version that's misaligned with everyone else's?

I'm simply using the latest version, so if we're meant to use an older version, then it's likely I am off.

**Comment by abailly-iohk** [comment]
```
% fourmolu --version
fourmolu 0.14.0.0
using ghc-lib-parser 9.6.3.20231014
```

**Pull request merged**
